# Generated by Django 3.2.5 on 2021-07-23 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meowtubeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='video_key',
            new_name='video_id',
        ),
    ]
