# Generated by Django 3.2.5 on 2021-07-27 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meowtubeapp', '0002_rename_video_key_comment_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='SubComment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meowtubeapp.comment'),
        ),
    ]
